Skip to content
zhaojingpo
edgetunnel
Repository navigation
代码
拉取请求
Actions
项目
Wiki
安全
统计
设置
Sync Fork Directly
Sync Fork Directly #1
All jobs
Run details
Workflow file for this run
.github/workflows/fork update.yml at be7dbb7
name: Sync Fork Directly

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    run-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/cmliu/edgetunnel.git
          git fetch upstream
          git checkout main
          git merge --allow-unrelated-histories upstream/main
          git push origin main
